memory_limit = 512M
upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 120
date.timezone = Europe/London
display_errors = On
error_reporting = E_ALL
opcache.enable = 1
opcache.validate_timestamps = 1
realpath_cache_size = 4096K
realpath_cache_ttl = 600
